### ISSUE TITLE
Link to dataset

### ISSUE THREAD

**Issue by devin-liu** [oxford-cs-deepnlp-2017/practical-2#4]
Can you guys put this link inside the practical?

http://www.clg.ox.ac.uk/tedcorpus

**Comment by iassael** [comment]
@devin-liu thanks for pointing it out, the link was in the first practical, but we added it here as well for clarification.

**Comment by bshillingford** [comment]
We are not using that data, but rather the April 2016 snapshot of this data: https://wit3.fbk.eu/
